2024-10-22 11:29:32,811 ERROR: Failed to fetch products from MongoDB: localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6717705ef9a2f8d49bd533c5, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> [in /Users/william/validate/inventory_validation/app/utils/inventory.py:52]
2024-10-22 11:30:24,103 INFO: Loaded main_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:67]
2024-10-22 11:30:24,106 INFO: 'processing_timestamp' column converted to datetime. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:117]
2024-10-22 11:30:24,779 INFO: Updated barcode for SKU 'DB-0175' with barcode '9002490256654'. [in /Users/william/validate/inventory_validation/app/routes/suggestions.py:122]
2024-10-22 11:30:25,998 INFO: Loaded finalized_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:67]
2024-10-22 11:30:26,008 INFO: Appended product 'DB-0175' to finalized_inventory. [in /Users/william/validate/inventory_validation/app/routes/suggestions.py:151]
2024-10-22 11:30:26,011 INFO: Finalized and removed product 'DB-0175' from main inventory. [in /Users/william/validate/inventory_validation/app/routes/suggestions.py:155]
2024-10-22 11:30:27,667 INFO: Saved finalized_inventory_staging.xlsx to S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:136]
2024-10-22 11:30:29,517 INFO: Saved main_inventory_staging.xlsx to S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:136]
2024-10-22 11:30:30,882 INFO: Loaded main_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:67]
2024-10-22 11:30:30,883 INFO: 'processing_timestamp' column converted to datetime. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:117]
2024-10-22 11:30:32,654 INFO: Saved main_inventory_staging.xlsx to S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:136]
2024-10-22 11:30:41,939 INFO: Loaded main_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:67]
2024-10-22 11:30:41,940 INFO: 'processing_timestamp' column converted to datetime. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:117]
2024-10-22 11:31:13,180 ERROR: Failed to fetch products from MongoDB: localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 671770c2f9a2f8d49bd533c6, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]> [in /Users/william/validate/inventory_validation/app/utils/inventory.py:52]
2024-10-22 11:32:09,331 INFO: Inventory Validation Startup [in /Users/william/validate/inventory_validation/app/__init__.py:30]
2024-10-22 11:32:23,369 INFO: Inventory Validation Startup [in /Users/william/validate/inventory_validation/app/__init__.py:30]
2024-10-22 11:32:40,197 INFO: Inventory Validation Startup [in /Users/william/validate/inventory_validation/app/__init__.py:30]
2024-10-22 11:33:24,342 INFO: Inventory Validation Startup [in /Users/william/validate/inventory_validation/app/__init__.py:30]
2024-10-22 11:33:39,469 INFO: Loaded main_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:32]
2024-10-22 11:33:39,471 INFO: 'processing_timestamp' column converted to datetime. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:82]
2024-10-22 11:34:09,026 INFO: Loaded main_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:32]
2024-10-22 11:34:09,027 INFO: 'processing_timestamp' column converted to datetime. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:82]
2024-10-22 11:34:09,032 INFO: Updated barcode for SKU 'DB-0055' with barcode '5449000177551'. [in /Users/william/validate/inventory_validation/app/routes/suggestions.py:77]
2024-10-22 11:34:09,815 INFO: Loaded finalized_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:32]
2024-10-22 11:34:09,819 INFO: Appended product 'DB-0055' to finalized_inventory. [in /Users/william/validate/inventory_validation/app/routes/suggestions.py:106]
2024-10-22 11:34:09,821 INFO: Finalized and removed product 'DB-0055' from main inventory. [in /Users/william/validate/inventory_validation/app/routes/suggestions.py:110]
2024-10-22 11:34:11,673 INFO: Saved finalized_inventory_staging.xlsx to S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:101]
2024-10-22 11:34:14,110 INFO: Saved main_inventory_staging.xlsx to S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:101]
2024-10-22 11:34:15,134 INFO: Loaded main_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:32]
2024-10-22 11:34:15,135 INFO: 'processing_timestamp' column converted to datetime. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:82]
2024-10-22 11:34:16,780 INFO: Saved main_inventory_staging.xlsx to S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:101]
2024-10-22 11:34:21,840 INFO: Loaded main_inventory_staging.xlsx from S3. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:32]
2024-10-22 11:34:21,841 INFO: 'processing_timestamp' column converted to datetime. [in /Users/william/validate/inventory_validation/app/utils/inventory.py:82]
